spring:
  data:
    mongodb:
      initialization-mode: always
      uri: mongodb://localhost:27017/reserva-restaurante
  application:
    name: reserva-restaurante
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG

springdoc:
  swagger-ui:
    path=/swagger-ui.html